// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `BannerIPrxHolder.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package TuiService;

public final class BannerIPrxHolder
{
    public
    BannerIPrxHolder()
    {
    }

    public
    BannerIPrxHolder(BannerIPrx value)
    {
        this.value = value;
    }

    public BannerIPrx value;
}
