// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `BannerIPrx.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package TuiService;

public interface BannerIPrx extends Ice.ObjectPrx
{
    public String GetInfo(String[] bannerid);

    public String GetInfo(String[] bannerid, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_GetInfo(String[] bannerid);

    public Ice.AsyncResult begin_GetInfo(String[] bannerid, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_GetInfo(String[] bannerid, Ice.Callback __cb);

    public Ice.AsyncResult begin_GetInfo(String[] bannerid, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_GetInfo(String[] bannerid, Callback_BannerI_GetInfo __cb);

    public Ice.AsyncResult begin_GetInfo(String[] bannerid, java.util.Map<String, String> __ctx, Callback_BannerI_GetInfo __cb);

    public String end_GetInfo(Ice.AsyncResult __result);
}
